version: "3.7"

services:
  database:
    image: postgres
    container_name: database_c_drivers
    restart: always
    ports: 
      - 5432:5432  
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=c_drivers
    volumes:
      - pgdata:/data/postgres  

  # app:
  #   build: .
  #   container_name: c_drivers
  #   ports: 
  #     - 3000:3000
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database
  #   depends_on: 
  #     - database  

volumes:
  pgdata:
    driver: local

